import type { CompanyDetails } from '../types/corporate';

export const COMPANY_DETAILS: CompanyDetails = {
  identity: {
    cin: 'U65923MH1995PTC088811',
    name: 'Siddhesh Capital Market Services Private Limited',
    status: 'Active',
    rocCode: 'RoC-Mumbai',
    registrationNumber: '088811',
    category: 'Company limited by shares',
    subCategory: 'Non-government company',
    classOfCompany: 'Private',
    dateOfIncorporation: '26 May 1995',
  },
  capital: {
    authorizedCapital: '₹80,00,00,000',
    authorizedCapitalWords: '₹80 Crore',
    paidUpCapital: '₹74,85,00,000',
    paidUpCapitalWords: '₹74.85 Crore',
    operatingRevenue: '₹100 Crore – ₹500 Crore',
    fiscalYear: 'For the fiscal year ending March 31, 2026',
    paidUpPercentage: 93.56,
  },
  contact: {
    address: '122, Maker Chambers III, Nariman Point, Mumbai, Maharashtra, India, 400021.',
    email: 'reshma@sekhsaria.com',
    phone: '099198 05234',
    city: 'Mumbai',
    pinCode: '400021',
  },
  management: [
    {
      name: 'Darshan Vijay Engineer',
      designation: 'Managing Director',
      category: 'executive',
      tenure: 'Active Signatory',
      description: 'Strategic leadership, institutional credit structuring, and executive board governance.',
    },
    {
      name: 'Nekzad Rohinton Dhunjibhoy',
      designation: 'Whole-time Director',
      category: 'executive',
      tenure: 'Active Signatory',
      description: 'Day-to-day operations, capital market transactions, and statutory compliance management.',
    },
    {
      name: 'Anupam Madan Pareek',
      designation: 'Director',
      category: 'board',
      tenure: 'Board Member',
      description: 'Corporate strategy, audit committee review, and financial oversight.',
    },
    {
      name: 'Ankush Vinod Pitale',
      designation: 'Director',
      category: 'board',
      tenure: 'Board Member',
      description: 'Risk management, credit underwriting parameters, and fiduciary advisory.',
    },
    {
      name: 'Bhanwarlal Jiwanmal Taparia',
      designation: 'Director',
      category: 'board',
      tenure: 'Board Member',
      description: 'Institutional partnerships, treasury policies, and long-term capital preservation.',
    },
    {
      name: 'Mitesh Jitendra Parekh',
      designation: 'Additional Director',
      category: 'additional',
      tenure: 'Additional Director',
      description: 'Commercial credit expansion, portfolio asset monitoring, and capital allocation.',
    },
    {
      name: 'Lakshit Janakbhai Desai',
      designation: 'Additional Director',
      category: 'additional',
      tenure: 'Additional Director',
      description: 'Compliance verification, market research, and regulatory liaison.',
    },
    {
      name: 'Neelam Rajendra Gaba',
      designation: 'Company Secretary',
      category: 'secretary',
      tenure: 'Key Managerial Personnel',
      description: 'Statutory filings, ROC-Mumbai correspondence, board secretarial affairs, and MCA compliance.',
    },
  ],
  operations: {
    principalActivity: 'Other credit granting and commercial loan operations',
    nicCode: '6592',
    lastAgmDate: '23 June 2025',
    sector: 'Non-Banking Financial & Credit Intermediation',
  },
};
